import React from "react";
import bgImage from "../../assets/images/cta-image.webp";
import { useNavigate } from 'react-router-dom';
export default function PrivacyPolicySection() {
    const navigate = useNavigate();

    const handleSellClick = () => {
        navigate("/vendor/login"); 
    };
    return (
        <div>
            {/* PrivacyPolicySection Content */}
            <section className="max-w-5xl mx-auto px-4 py-12 text-gray-800 text-[15px] leading-relaxed">
                <h1 className="text-3xl font-heading text-black leading-tight mt-2 pb-6">
                    PRIVACY POLICY
                </h1>

                <p className="mb-6">
                    Your privacy is important to us at <strong>Sellaids</strong>. This Privacy Policy governs your visit to our website and explains how we collect, safeguard and disclose information resulting from your use of our services. By accessing or using Sellaids, you agree to the collection and use of information in accordance with this policy. If you do not agree with these terms, please do not use our services.
                </p>


                {/* Definitions */}
                <h2 className="text-2xl font-heading text-black mt-8 mb-4">Definitions</h2>
                <ul className="list-disc ml-6 space-y-2">
                    <li><strong>Service:</strong> Refers to the Sellaids website and its associated services.</li>
                    <li><strong>Personal Data:</strong> Data about a living individual who can be identified from that data or from other information either in our possession or likely to come into our possession.</li>
                    <li><strong>Usage Data:</strong> Automatically collected data generated by the use of the service or from the service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>Cookies:</strong> Small files stored on your device (computer or mobile) that track information.</li>
                    <li><strong>Data Controller:</strong> A person or legal entity that determines the purposes and means of processing personal data. For this Privacy Policy, Sellaids acts as the Data Controller.</li>
                    <li><strong>Data Processors (Or Service Providers):</strong> Third parties who process data on behalf of the Data Controller to enhance service delivery.</li>
                    <li><strong>Data Subject:</strong> Any living individual who is the subject of Personal Data.</li>
                    <li><strong>The User:</strong> The individual using our Service, corresponding to the Data Subject.</li>
                </ul>
                {/* Section 1 */}
                <h2 className="text-2xl font-heading text-black mt-8 mb-4">1. Information We Collect</h2>
                <h3 className="font-semibold mt-4">1.1 Personal Information</h3>
                <p>When using our services, we may request certain personally identifiable information that can be used to contact or identify you, including:</p>
                <ul className="list-disc ml-6 space-y-2 mt-2">
                    <li><strong>Contact Information:</strong> Name, email address, phone number and mailing address.</li>
                    <li><strong>Account Information:</strong> Username and password.</li>
                    <li><strong>Payment Information:</strong> Credit card details are processed through secure payment gateways.</li>
                    <li><strong>Demographic Information:</strong> Age, gender, location and preferences.</li>
                </ul>

                <h3 className="font-semibold mt-6">1.2 Automatically Collected Information</h3>
                <p>We may collect information automatically about your device and how you use our services. This can include:</p>
                <ul className="list-disc ml-6 space-y-2 mt-2">
                    <li><strong>Device Information:</strong> IP address, browser type, operating system and device identifiers.</li>
                    <li><strong>Usage Data:</strong> Pages visited, time spent on those pages, referral URLs and other interaction metrics.</li>
                </ul>

                <h3 className="font-semibold mt-6">1.3 Cookies and Tracking Technologies</h3>
                <p>Sellaids uses cookies and similar tracking technologies to monitor user activity on our website. These tools help us:</p>
                <ul className="list-disc ml-6 space-y-2 mt-2">
                    <li>Recognize your device and remember your preferences.</li>
                    <li>Analyse site traffic and user behaviour to improve our services.</li>
                    <li>Customize content and advertisements based on your interests.</li>
                </ul>
                <p className="mt-2">Examples of cookies we use include:</p>
                <ul className="list-disc ml-6 space-y-2 mt-2">
                    <li><strong>Session Cookies:</strong> For operating our services.</li>
                    <li><strong>Preference Cookies:</strong> To remember your preferences.</li>
                    <li><strong>Security Cookies:</strong> To enhance security.</li>
                    <li><strong>Advertising Cookies:</strong> To deliver relevant ads.</li>
                </ul>
                <p className="mt-2">
                    You can manage your cookie preferences through your browser settings. However, disabling cookies may affect your ability to access certain features of our website.
                </p>

                {/* Section 2 */}
                <h2 className="text-2xl font-heading text-black mt-8 mb-4">2. How We Use Your Information</h2>
                <p>The information we collect may be utilized for various purposes, including:</p>
                <ul className="list-disc ml-6 space-y-2">
                    <li>Providing and maintaining our services.</li>
                    <li>Processing transactions and managing your account.</li>
                    <li>Sending you updates, newsletters and promotional materials.</li>
                    <li>Improving our services through data analysis and user feedback.</li>
                    <li>Ensuring legal compliance and protecting the rights and safety of users.</li>
                </ul>

                {/* Section 3 */}
                <h2 className="text-2xl font-heading text-black mt-8 mb-4">3. Data Retention</h2>
                <p>We will retain your personal information only for as long as necessary to fulfil the purposes outlined in this Privacy Policy. After this period, we may retain usage data for internal analysis. We will retain personal data as required by law or to resolve disputes and enforce agreements.</p>

                {/* Section 4 */}
                <h2 className="text-2xl font-heading text-black mt-8 mb-4">4. Security of Your Information</h2>
                <p>We take the security of your personal information seriously. We implement various security measures to protect against unauthorized access, alteration, disclosure or destruction of your information. This includes the use of SSL encryption for sensitive data during transmission. However, please note that no method of transmission over the Internet is completely secure.</p>

                {/* Section 5 */}
                <h2 className="text-2xl font-heading text-black mt-8 mb-4">5. Sharing Your Information</h2>
                <p>We do not sell or rent your personal information to third parties. However, we may share your information with:</p>
                <ul className="list-disc ml-6 space-y-2">
                    <li><strong>Service Providers:</strong> Trusted third-party vendors who assist us in providing our services and processing your data.</li>
                    <li><strong>Legal Authorities:</strong> In compliance with the law or to protect our rights and the safety of others.</li>
                    <li><strong>Business Transactions:</strong> If we undergo a merger, acquisition or sale of assets, your information may be transferred as part of that transaction.</li>
                </ul>

                {/* Section 6 */}
                <h2 className="text-2xl font-heading text-black mt-8 mb-4">6. Your Rights Regarding Your Information</h2>
                <p>As a user, you have rights regarding your personal data, including:</p>
                <ul className="list-disc ml-6 space-y-2">
                    <li><strong>Access:</strong> Request access to the personal information we hold about you.</li>
                    <li><strong>Correction:</strong> Request correction of any inaccurate or incomplete information.</li>
                    <li><strong>Deletion:</strong> Request the deletion of your personal data, subject to legal obligations.</li>
                    <li><strong>Objection:</strong> Object to our processing of your personal data for marketing purposes.</li>
                </ul>
                <p className="mt-2">
                    To exercise any of these rights, please contact us at{" "}
                    <a href="mailto:contact@sellaids.com" className="text-orange-600">
                        contact@sellaids.com
                    </a>
                </p>

                {/* Section 7 */}
                <h2 className="text-2xl font-heading text-black mt-8 mb-4">7. Third-Party Links</h2>
                <p>Our website may contain links to other websites that are not operated by us. We do not control these sites and are not responsible for their content or privacy practices. We encourage you to review the privacy policies of any third-party sites you visit.</p>

                {/* Section 8 */}
                <h2 className="text-2xl font-heading text-black mt-8 mb-4">8. Changes to This Privacy Policy</h2>
                <p>We may update this Privacy Policy periodically to reflect changes in our practices or applicable laws. We will notify you of significant changes by posting the new policy on this page and updating the effective date. We encourage you to review this policy regularly for any updates.</p>

                {/* Section 9 */}
                <h2 className="text-2xl font-heading text-black mt-8 mb-4">9. Contact Us</h2>
                <p>If you have any questions, concerns or requests regarding this Privacy Policy or our data practices, please reach out to us at{" "}
                    <a href="mailto:contact@sellaids.com" className="text-orange-600">
                        contact@sellaids.com
                    </a>. We are committed to addressing your inquiries promptly.
                </p>
            </section>

            {/* ✅ Responsive CTA Section Bottom */}
            <section
                className="relative h-[300px] sm:h-[400px] md:h-[500px] flex items-center justify-center md:justify-start bg-cover bg-center"
                style={{ backgroundImage: `url(${bgImage})` }}
            >
                {/* Overlay */}
                <div className="absolute inset-0 bg-black bg-opacity-30"></div>

                {/* Content */}
                <div className="relative z-10 px-6 md:pl-12 max-w-3xl text-center md:text-left">
                    <h2 className="text-white text-2xl sm:text-3xl md:text-4xl font-heading leading-snug">
                        Resell Your Luxury Bags, Designer Outfits, Menswear, Kidswear And
                        More—Because Fashion Deserves A Second Life.
                    </h2>

                    <button onClick={handleSellClick} className="mt-6 px-6 py-3 bg-orange-500 text-white font-semibold hover:bg-orange-600 transition">
                        SELL NOW
                    </button>
                </div>
            </section>
        </div>
    );
}
