<?php
/**
 * Shared Programs data — used by activities.php (Programs page),
 * the 8 program-*.php detail pages, and the header nav dropdown.
 * To change a picture, edit its path here. Square images look best.
 */
$PROGRAMS = [
    'art-craft' => [
        'name'    => 'Art & Craft',
        'icon'    => 'images/activities/art-craft.jpg',
        'tint'    => 'c1',
        'grad'    => 'linear-gradient(140deg, #ff9ec4, #ff7fb1)',
        'tagline' => 'Colours, creativity and happy hands — every masterpiece tells a story.',
        'items'   => [
            'Fun Painting'                  => 'images/activities/fun-painting.jpg',
            'Creative crafts'               => 'images/activities/creative-crafts.jpg',
            'Clay modelling'                => 'images/activities/clay-modelling.jpg',
            'Collage-making'                => 'images/activities/collage-making.jpg',
            'Scrapbooking'                  => 'images/activities/scrapbooking.jpg',
            'Gratitude tree'                => 'images/activities/gratitude-tree.jpg',
            'Small DIY projects'            => 'images/activities/diy-projects.jpg',
            'Reminiscence and Memory Boxes' => 'images/activities/memory-boxes.jpg',
        ],
    ],
    'hobbies-recreation' => [
        'name'    => 'Hobbies & Recreation',
        'icon'    => 'images/activities/hobbies-recreation.jpg',
        'tint'    => 'c2',
        'grad'    => 'linear-gradient(140deg, #ffc46b, #f5a938)',
        'tagline' => 'Rediscover old passions and find delightful new ones.',
        'items'   => [
            'Therapeutic Colouring' => 'images/activities/therapeutic-colouring.jpg',
            'Drawing Activities'    => 'images/activities/drawing.jpg',
            'Reading'               => 'images/activities/reading.jpg',
            'Writing & Journaling'  => 'images/activities/journaling.jpg',
            'Story Telling'         => 'images/activities/story-telling.jpg',
            'Indoor Herb Gardens'   => 'images/activities/herb-gardens.jpg',
            'Dancing'               => 'images/activities/dancing.jpg',
            'Engaging Art'          => 'images/activities/engaging-art.jpg',
            'Knitting and Crafting' => 'images/activities/knitting.jpg',
        ],
    ],
    'cognitive-games' => [
        'name'    => 'Cognitive Games',
        'icon'    => 'images/activities/cognitive-games.jpg',
        'tint'    => 'c3',
        'grad'    => 'linear-gradient(140deg, #8fdca0, #5fc47a)',
        'tagline' => 'Brain-boosting fun that keeps minds sharp, curious and smiling.',
        'items'   => [
            'Memory boosters'              => 'images/activities/memory-boosters.jpg',
            'Decision making games'        => 'images/activities/decision-games.jpg',
            'Strategy thinking games'      => 'images/activities/strategy-games.jpg',
            'Brain Stimulating activities' => 'images/activities/brain-stimulating.jpg',
            'Visual games'                 => 'images/activities/visual-games.jpg',
            'Comforting activities'        => 'images/activities/comforting.jpg',
            'Treat Trolley'                => 'images/activities/treat-trolley.jpg',
            'Physical Recreation'          => 'images/activities/physical-recreation.jpg',
        ],
    ],
    'music-movement' => [
        'name'    => 'Music & Movement',
        'icon'    => 'images/activities/music-movement.jpg',
        'tint'    => 'c4',
        'grad'    => 'linear-gradient(140deg, #93a9ff, #5b7cfa)',
        'tagline' => 'Creating moments of joy through music, laughter, and togetherness!',
        'items'   => [
            'Karaoke'                  => 'images/activities/karaoke.jpg',
            'Charades'                 => 'images/activities/charades.jpg',
            'Interactive sing-alongs'  => 'images/activities/sing-alongs.jpg',
            'Listening Sessions'       => 'images/activities/listening.jpg',
            'Jamming'                  => 'images/activities/jamming.jpg',
            'Musical Bingo'            => 'images/activities/musical-bingo.jpg',
            'Props dancing'            => 'images/activities/props-dancing.jpg',
            'Musical games'            => 'images/activities/musical-games.jpg',
            'Learn musical instrument' => 'images/activities/learn-instrument.jpg',
        ],
    ],
    'mindfulness' => [
        'name'    => 'Mindfulness',
        'icon'    => 'images/activities/mindfulness.jpg',
        'tint'    => 'c5',
        'grad'    => 'linear-gradient(140deg, #8fd9cb, #52bda7)',
        'tagline' => 'Gentle care for body and mind — calm, balance and easy movement.',
        'items'   => [
            'Meditation & Mindfulness' => 'images/activities/meditation.jpg',
            'Yoga'                     => 'images/activities/yoga.jpg',
            'Gentle Stretching'        => 'images/activities/stretching.jpg',
            'Easy Sit-down Exercises'  => 'images/activities/sit-down-exercises.jpg',
        ],
    ],
    'social-jollies' => [
        'name'    => 'Social Jollies',
        'icon'    => 'images/activities/social-jollies.jpg',
        'tint'    => 'c6',
        'grad'    => 'linear-gradient(140deg, #ffa98a, #f57d52)',
        'tagline' => 'Clubs, circles and celebrations — friendship is the best activity.',
        'items'   => [
            'Book Club'            => 'images/activities/book-club.jpg',
            'Photo Sharing Circle' => 'images/activities/photo-sharing.jpg',
            'Reading club'         => 'images/activities/reading-club.jpg',
            'Reminiscence Group'   => 'images/activities/reminiscence-group.jpg',
            'Culinary Adventures'  => 'images/activities/culinary.jpg',
            'Garden Club'          => 'images/activities/garden-club.jpg',
        ],
    ],
    'digital-literacy' => [
        'name'    => 'Digital Literacy',
        'icon'    => 'images/activities/digital-literacy.jpg',
        'tint'    => 'c7',
        'grad'    => 'linear-gradient(140deg, #b0a4ff, #8672f5)',
        'tagline' => 'Confidence in the digital world — from video calls to AI tools.',
        'items'   => [
            'Security & Safety'       => 'images/activities/security.jpg',
            'Essential Skills'        => 'images/activities/essential-skills.jpg',
            'Entertainment & Hobbies' => 'images/activities/entertainment.jpg',
            'AI-powered tools'        => 'images/activities/ai-tools.jpg',
        ],
    ],
    'one-on-one' => [
        'name'    => 'One-on-One',
        'icon'    => 'images/activities/one-on-one.jpg',
        'tint'    => 'c8',
        'grad'    => 'linear-gradient(140deg, #ffd95e, #f5b820)',
        'tagline' => 'One-on-one visits for many fun & stimulating activities.',
        'items'   => [
            'One-on-one visits' => 'images/activities/one-on-one-visits.jpg',
        ],
    ],
];
